modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Create-Freezedown/Create-Thermology/issues"
[[mods]]
modId="create_freezedown"
version="${file.jarVersion}"
displayName="Create: Thermology"
displayURL="https://github.com/Create-Freezedown/Create-Thermology"
logoFile="create_freezedown.png"
credits="cannonmoose, krystal, dacodia"
authors="PouffyDev"
description='''
Core mod for Create: Freezedown
'''
[[dependencies.create_freezedown]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.create_freezedown]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
